print("  *       *      *     ")
print("                  *    ")
print("    *     *            ")
print("            *       *  ")
print("    *                  ")
print("           HHHHHH      ")
print("   *       HHHHHH      ")
print("         HHHHHHHHHHH   ")
print("         *  @  @  *    ")
print("    *   *    ^    *    ")
print("          *      *     ")
print("     *    sssssss      ")
print("   *      ssssssss     ")
print("          *  s  *      ")
print("       *     s     *   ")
print("      *      s      *  ")
print("       *           *   ")
print("          *  *  *      ")